spring:
  profiles:
    active: dev
    server:
      servlet:
        context-path: /common
      port: 10900

  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/sso?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver