wxpay:
  #https://pay.weixin.qq.com/wiki/doc/apiv3/open/pay/chapter2_7_2.shtml
  # 微信支付相关参数
  # 商户号
  mch-id: 1497984412
  # 商户API证书序列号
  mch-serial-no: 457781397EF26D03680D05C7C5C1164003FEDD8B
  # 商户私钥文件
  private-key-path: D://apiclient_key.pem
  # APIv3密钥
  api-v3-key: qianfengjiaoyuceshihao1234567891
  # APPID
  appid: wx632c8f211f8122c6
  # 微信服务器地址
  domain: https://api.mch.weixin.qq.com
  # 接收结果通知地址
  # 注意：每次重新启动ngrok，都需要根据实际情况修改这个配置
  notify-domain: http://z2r2zh.natappfree.cc
  # APIv2密钥
  partnerKey: qianfengjiaoyuceshihao1234567891
