<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <artifactId>odin-parent</artifactId>
    <groupId>com.aladdin.mis</groupId>
    <version>0.1-SNAPSHOT</version>
    <relativePath>../odin-parent/pom.xml</relativePath>
  </parent>

  <artifactId>extract-sso</artifactId>
  <version>0.1-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>extract-sso</name>
  <!-- FIXME change it to the project's website -->
  <url>http://www.example.com</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
      <shiro.version>2.0.5</shiro.version>
  </properties>

  <dependencies>
      <dependency>
          <groupId>com.aladdin.mis</groupId>
          <artifactId>extract-common</artifactId>
          <version>${project.version}</version>
      </dependency>
      <!-- Shiro -->
      <dependency>
          <groupId>org.apache.shiro</groupId>
          <artifactId>shiro-spring-boot-starter</artifactId>
          <classifier>jakarta</classifier>
          <version>${shiro.version}</version>
          <exclusions>
              <exclusion>
                  <groupId>org.apache.shiro</groupId>
                  <artifactId>shiro-crypto-cipher</artifactId>
              </exclusion>
              <exclusion>
                  <groupId>org.apache.shiro</groupId>
                  <artifactId>shiro-crypto-hash</artifactId>
              </exclusion>
              <exclusion>
                  <groupId>org.apache.shiro</groupId>
                  <artifactId>shiro-web</artifactId>
              </exclusion>
              <exclusion>
                  <groupId>org.apache.shiro</groupId>
                  <artifactId>shiro-spring</artifactId>
              </exclusion>
          </exclusions>
      </dependency>
      <dependency>
          <groupId>org.apache.shiro</groupId>
          <artifactId>shiro-web</artifactId>
          <classifier>jakarta</classifier>
          <version>${shiro.version}</version>
      </dependency>
      <dependency>
          <groupId>org.apache.shiro</groupId>
          <artifactId>shiro-spring</artifactId>
          <classifier>jakarta</classifier>
          <version>${shiro.version}</version>
          <exclusions>
              <exclusion>
                  <groupId>org.apache.shiro</groupId>
                  <artifactId>shiro-web</artifactId>
              </exclusion>
          </exclusions>
      </dependency>


  </dependencies>

</project>
