server:
  port: 8002
  servlet:
    context-path: /getway
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: extract-bill
          uri: lb://extract-bill
          filters:
            - AddRequestHeader=X-Request-Foo, Bar
          predicates:
            - Path=/bill/**
    config:
      enabled: true
    nacos:
      discovery:
        server-addr: 121.199.72.15:8848
        namespace: dev
      config:
        server-addr: 121.199.72.15:8848
        namespace: dev
#        extension-configs:
#          - data-id: getway-router
#            group: GETWAY_GROUP
#          - data-id: application-db.yml
#            group: common_group
#          - data-id: application-redis.yml
#            group: common_group
#          - data-id: application-third.yml
#            group: common_group
#          - data-id: application-applets.yml
#            group: common_group
