server:
  port: 80
  servlet:
    context-path: /om
spring:
#  cloud:
#    config:
#      enabled: false
#    nacos:
#      discovery:
#        server-addr: 121.199.72.15:8848
#        namespace: dev
#      config:
#        server-addr: 121.199.72.15:8848
#        namespace: dev
  datasource:
    username: root
    password: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/company?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  # rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true
#  data:
#    mongodb:
#      uri:  mongodb://121.199.72.15:27017/company
#      database: company
  mvc:
    view:
      prefix: /
      suffix: .html
    static-path-pattern: /static/**/**
  thymeleaf:
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    #客户端超时时间单位是毫秒 默认是2000
    timeout: 5000
    #数据库数量
    database: 8
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait: -1
        # 最大活跃连接数，负数为不限制
        max-active: -1
  # nacos 配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#  mybatis 驼峰
mybatis:
  configuration:
    map-underscore-to-camel-case: true

global:
  # 是否开启校验
  verify:
    # 全部的校验
    enable: true
    # 验证码的校验
    code: true
    # 手机短信的校验
    sms: true
  redis:
    enable: true
  sso:
    enable: true
    url: http://localhost:8081/sso
  appKey: 10001
  appSecret: 10001

