spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  datasource:
    username: root
    password: hsb@test@2!k25kHF
    url: jdbc:mysql://43.142.17.3:6002/smart?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:/mybatis-mapper/system/*.xml
  type-aliases-package: com.aladdin.mis.entity
  configuration:
    map-underscore-to-camel-case: true

